# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6009a4a6f6cc160bb8d3e132b749e1d75c059368f3df7fc3de75b0bba5a64c7916ab4bc79160fc2c5687b47d3d5bcbb246f0899d2edcb5a862db7dcaea91ef44

test:
  secret_key_base: f56db49b336d81a1dd6aefa3deda4e17024043adfe5d0582edfc122e320506d51c423dce8bb610d257bed6df723f154a186935d059bfcc16ea1b3e5893fcd3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
